### ISSUE TITLE
RangeError for port argument

### ISSUE THREAD

**Issue by saopayne** [iQubeLabs/sdp_search_members_node#1]
I suspect this is due to the nodejs6 http API. P.S. I'm running NodeJS6

_saopayne@Oyewales-MacBook-Pro:~/Documents/Work/iQubeLabs/sdp_search_members_node$ npm start

> sdp_search_members_node@0.0.1 start /Users/saopayne/Documents/Work/iQubeLabs/sdp_search_members_node
> node app.js

WARNING: No configurations found in configuration directory:/Users/saopayne/Documents/Work/iQubeLabs/sdp_search_members_node/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
loading all app routes
**internal/net.js:17
    throw new RangeError('"port" argument must be >= 0 and < 65536');
    ^

RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1377:5)
    at EventEmitter.listen*\* (/Users/saopayne/Documents/Work/iQubeLabs/sdp_search_members_node/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/saopayne/Documents/Work/iQubeLabs/sdp_search_members_node/app.js:13:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)

npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! sdp_search_members_node@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sdp_search_members_node@0.0.1 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sdp_search_members_node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sdp_search_members_node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sdp_search_members_node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/saopayne/Documents/Work/iQubeLabs/sdp_search_members_node/npm-debug.log_

**Comment by perfectmak** [comment]
It is possible. I'm using node 5 and I set the minimum engine requirements to that.

But the error seems to be with the port number.

Could you do some investigating as to if your port number is actually loaded.
I'll try testing with node6 too

**Comment by perfectmak** [comment]
Actually, it was an error importing the config.js module, it has been fixed with the latest commit.

Pull in the latest update.
